### ISSUE TITLE
[Bug] Season 1 Level 3 links to a GitHub video which is now private

### ISSUE THREAD

**Issue by pbgcommits** [skills/secure-code-game#110]
### Summary

Line 41 in Season-1/Level-3/solution.py contains this link: https://youtu.be/sQGxdwRePh8 which is no longer accessible.

**Comment by za** [comment]
Maybe we can can remove the hyperlink for now.

**Comment by jkcso** [comment]
Done thanks for reporting!

**Comment by za** [comment]
The text contains youtube link is removed now.
