### ISSUE TITLE
[Question] Level 3 Output

### ISSUE THREAD

**Issue by QaidVoid** [skills/secure-code-game#25]
The original behavior of the `get_prof_picture` function was to return `None` after checking denylist. But, `hack.py` expects the function to return the path instead of `None`. Wouldn't it make more sense to return early by checking if the returned value is `None` instead of just comparing the base directory and the output base directory? It should allow the functions to return `None` if invalid path is passed.

**Comment by jkcso** [comment]
Good point, please feel free to submit a PR :-)

**Comment by Cito** [comment]
Agree with @QaidVoid, the goal of getting `hack.py` to pass cannot be reached otherwise. His PR looks good to me.
