### ISSUE TITLE
[Bug] Level-1 Quantity Bug

### ISSUE THREAD

**Issue by TravisRistowCvna** [skills/secure-code-game#28]
**Describe the bug**
 Level one has an additional bug/vulnerability in some flows it does not account for the quantity

**To Reproduce**
1. Update Test to test with >1 quantity
2. Run test with solution
3. See Failure

**Expected behavior**
As a user when running the solution, I should expect it to return Success with any valid test values _(>1 quantity)_

**Comment by jkcso** [comment]
Can you open a PR please to understand more?
