### ISSUE TITLE
[Bug] - Unintended Level One win 

### ISSUE THREAD

**Issue by a2937** [skills/secure-code-game#43]
### Summary

There is another unintended way to win level one's challenge at avoiding the underflow and overflow errors. By converting all number types into the `int` data type, the bits for the number storage expands to be large enough to handle pretty much any number the machine can handle. However the tests shouldn't allow it to pass. As it is a store, dollars and cents need to be accounted for. 

### How to reproduce

1. Go to the level one challenge
2. Open `code.py` 
3. Cast every number to an integer like the attached code. 
4. Run the tests 
5. See error

Please include screenshots.

![The Challenge passing](https://github.com/skills/secure-code-game/assets/9373245/4faab16a-02cb-440b-ab09-e5318aa135d7)

### Additional context

Here's the full code that breaks the challenge:

```py
from collections import namedtuple

Order = namedtuple('Order', 'id, items')
Item = namedtuple('Item', 'type, description, amount, quantity')

def validorder(order: Order):
    net = 0
    
    for item in order.items:
        if item.type == 'payment':
            net += int(item.amount)
        elif item.type == 'product':
            net -= int(item.amount * item.qu
![Capture](https://github.com/skills/secure-code-game/assets/9373245/4faab16a-02cb-440b-ab09-e5318aa135d7)
antity)
        else:
            return("Invalid item type: %s" % item.type)
    
    if net != 0:
        return("Order ID: %s - Payment imbalance: $%0.2f" % (order.id, net))
    else:
        return("Order ID: %s - Full payment received!" % order.id)
```

**Comment by hectorsector** [comment]
Thanks for the report @a2937! I see you opened a PR so I asked our technical reviewers to look at it. It may take them some time.
