### ISSUE TITLE
[Bug] Readme file not updated after creating the repository

### ISSUE THREAD

**Issue by marcosolina** [skills/secure-code-game#47]
Hi guys, thanks for this course and also the other available in the skills section.
I was trying to follow the instruction, so I have create the new repo and waited for the readme file to be updated, as decribed in the initial readme file.

![image](https://github.com/skills/secure-code-game/assets/26163844/56254e1a-6946-4a60-9823-f983bbf9e0c4)

But unfortunately, even after the "Initial commit" action has completed without errors, the readme file is not updated. Any suggestions? 
Here some extra info:
- [New repo](https://github.com/marcosolina/skills-secure-code-game)

Thanks

![image](https://github.com/skills/secure-code-game/assets/26163844/b0db8fa1-2b91-47c3-a428-2e3cf300f2bd)

**Comment by jkcso** [comment]
Hi @marcosolina! The readme file is not expected to be updated after you perform those steps. I have checked your new repo and all is working as expected.
