### ISSUE TITLE
[Bug] Level 1 - Fixing one security problem should not introduce new security issues

### ISSUE THREAD

**Issue by evarga** [skills/secure-code-game#54]
### Summary

The provided `solution.py` contains a dangerous bug that allows attackers to easily blow up a system and potentially make it unavailable.

### How to reproduce

Add the following test case to `hack.py` and change line number 2 to import `solution` instead of `code` (notice that the `quantity` is a `float` number):
```
# Invalid input should not blow up the system
def test_6(self):
    tv = c.Item(type='product', description='tv', amount=1000, quantity=1.5)
    order_1 = c.Order(id='1', items=[tv])
    try:
        c.validorder(order_1)
    except:
        self.fail("Unhandled exception occured in the target system!")
```
### How to Fix this Bug

Input validation should be expanded to also check data types besides testing allowed range of values. This specific bug, caused by using a non-integer quantity, is due to insufficient attention to requirements engineering. In some systems it is OK to buy half of something, but here it was assumed to be a positive integer.

**Comment by jkcso** [comment]
Thank you! Your feedback is fantastic and you have provided an excellent write-up. Please feel free to submit a PR that closes this issue :-)

**Comment by jkcso** [comment]
Fixed, thank you!
