### ISSUE TITLE
[Documentation] Season 2/Level 2 - Typo in the Code Comment

### ISSUE THREAD

**Issue by evarga** [skills/secure-code-game#60]
### Summary

There is a typo in the code comment in the file `Season-2/Level-2/solution/solution_test.go`.

### How to reproduce

Line number 5 should be changed from:

`This file is a copy of main_test.go and solution_test.go`

to read as:

`This file is a copy of code_test.go and hack_test.go`

**Comment by rsese** [comment]
Fixed by https://github.com/skills/secure-code-game/pull/61
