### ISSUE TITLE
[Bug] Season 2 ; Level 5 - Incomplete documentation for Codespace users.

### ISSUE THREAD

**Issue by ariyonaty** [skills/secure-code-game#84]
### Summary

The documentation for codespace users is only partially complete. 
Snippet for context (from [hack-1.js](https://github.com/skills/secure-code-game/blob/main/Season-2/Level-5/hack-1.js#L7C1-L10C37))
```js
// Please note that if you are inside a codespace, it is not possible to perform step 1. For
// this reason, please create a local copy for the file 'index.html'. You can do so by copying 
// and pasting the contents of 'index.html' in a local file so that you can open it in a browser.
// Then, follow the remaining steps.
```

The key detail here missing is that the same series of steps is necessary with `code.js`, as it is referenced in the HTML [here](https://github.com/skills/secure-code-game/blob/main/Season-2/Level-5/index.html#L54). Therefore, only copying `index.html` to local environment will result in errors like:
```js
ReferenceError: CryptoAPI is not defined
```

### How to reproduce

Copy _only_ `index.html` to local environment and open in browser. Attempt to replicate steps outlined in the "hack-x.js". 
Screenshot:
![image](https://github.com/skills/secure-code-game/assets/18715356/ecca49a5-f416-45e7-9190-e7bcbfcc744a)

### Additional context

On a side note, I imagine codespace users (such as myself) would like a solution that fits under the Codespace umbrella. Proposing via a PR a solution that worked for me and hopefully for others as well.

**Comment by jkcso** [comment]
@ariyonaty Great work, thanks a lot! I will accept the changes after I will change the language on the instructions a bit.
If you ever want to give back to the community, feel free to have a look on our contributions guideline!
