### ISSUE TITLE
[Bug] Warnings in the CodeQL Analysis workflow

### ISSUE THREAD

**Issue by sinsukehlab** [skills/secure-code-game#86]
### Summary

Deprecated Node.js version

### How to reproduce

1. Go to **Actions** tab
2. Click on a run from the CodeQL Analysis workflow
3. Scroll down to **Annotations**
4. See warnings

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, github/codeql-action/init@v2, github/codeql-action/autobuild@v2, github/codeql-action/analyze@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/

**Comment by jkcso** [comment]
@sinsukehlab Thanks for this! Please feel free to open a PR closing it and I will accept it :-)
