### ISSUE TITLE
missing package.json file

### ISSUE THREAD

**Issue by jackfusion** [skills/secure-code-game#98]
### Discussed in https://github.com/skills/secure-code-game/discussions/97

<div type='discussions-op-text'>

<sup>Originally posted by **jackfusion** June 14, 2024</sup>
I am running this on windows 11 and the package.json file is missing from the season foleders.  How can I get a copy of these files?</div>

**Comment by nguyenalex836** [comment]
Hello @jackfusion! It looks like you received a response from one of our team members [here](https://github.com/skills/secure-code-game/discussions/97#discussioncomment-9798882) - I'l go ahead and close out this issue 💛
